markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Bertrand SIMONNET
url: http://iwky911.github.com
description: Bertrand's blog
gravatar_url: http://www.gravatar.com/avatar/4833d01f26258864c0a6d4d17e14ab51.png